bots = [  # 20.07.2016
    u'AHbot',
    u'Aibot',
    u'AvocatoBot',
    u'Balabot',
    u'CarsracBot',
    u'CinBot',
    u'CinBotique',
    u'CodeMonkBot',
    u'CompBot',
    u'Conversion script',  # added
    u'Flow talk page manager',
    u'HydrizBot',
    u'Interwicket',
    u'JAnDbot',
    u'JackBot',
    u'KR',
    u'KamikazeBot',
    u'LA2-bot',
    u'LEANSErBot',
    u'LXbot',
    u'LingvistBot',
    u'Luckas-bot',
    u'Maintenance script',
    u'Makecat-bot',
    u'MediaWiki default',
    u'MediaWiki message delivery',
    u'MerdiginnBot',
    u'MonoBot',
    u'MuratorBot',
    u'RobotGMwikt',
    u'RoggBot',
    u'RuBot',
    u'SKbot',
    u'SpaceBirdyBot',
    u'Structor',
    u'TrudoBot',
    u'UT-interwiki-Bot',
    u'VPBot',
    u'ValentinsBot',
    u'Vitalik3Bot',
    u'Vitalik7Bot',
    u'VitalikBot',
    u'VolkovBot',
    u'WarddrBOT',
    u'WelcomeUserBot',
    u'WeshaBot',
    u'YS-Bot',
    u'РобоСтася',
    u'Управляющий Flow-обсуждением',
    u'タチコマ robot',
]
